
const ASSETS = "../assets/";


window.products = [
  { id: 1, name: "Figura Sakura Miku", price: 20000,
    img: ASSETS + "Sakuramiku.png",
    images: [ASSETS + "Sakuramiku.png"],
    desc: "Figura oficial de Hatsune Miku." },
  { id: 2, name: "Figura Hornet", price: 20000,
    img: ASSETS + "Hornet.jpg",
    images: [ASSETS + "Hornet.jpg"],
    desc: "Figura de Hollow Knight: Silksong." },
  { id: 3, name: "Nendoroid The Knight", price: 20000,
    img: ASSETS + "NendoroidHollowKnight.png",
    images: [ASSETS + "NendoroidHollowKnight.png"],
    desc: "Nendoroid oficial de 'The Knight'." },
  { id: 4, name: "Pack Library of Ruina", price: 25000,
    img: ASSETS + "LoRKeyChain+ArtBook.png",
    images: [ASSETS + "LoRKeyChain+ArtBook.png"],
    desc: "Set de llaveros + libro de arte." },
  { id: 5, name: "Poster Library of Ruina", price: 5000,
    img: ASSETS + "PosterLoR.jpg",
    images: [ASSETS + "PosterLoR.jpg"],
    desc: "Póster con Binah, Roland y Gebura." },
  { id: 6, name: "Replica Invitacion LoR", price: 10000,
    img: ASSETS + "InvitacionLoR.jpg",
    images: [ASSETS + "InvitacionLoR.jpg"],
    desc: "Réplica de invitación a la biblioteca." },
  { id: 7, name: "Gato Básico", price: 5000,
    img: ASSETS + "BasicCat.png",
    images: [ASSETS + "BasicCat.png"],
    desc: "Gato Básico de The Battle Cats." },
  { id: 8, name: "Gato Hacha", price: 5000,
    img: ASSETS + "AxeCat.png",
    images: [ASSETS + "AxeCat.png"],
    desc: "Gato Hacha de The Battle Cats." },
  { id: 9, name: "Figura DoomSlayer", price: 20000,
    img: ASSETS + "DoomSlayer.png",
    images: [ASSETS + "DoomSlayer.png"],
    desc: "Figura oficial de Doom: Dark Ages." },
  { id: 10, name: "Figura Medic", price: 15000,
    img: ASSETS + "medic.png",
    images: [ASSETS + "medic.png"],
    desc: "Figura del personaje Medic (TF2)." },
  { id: 11, name: "Figura Spy", price: 15000,
    img: ASSETS + "spy.png",
    images: [ASSETS + "spy.png"],
    desc: "Figura del personaje Spy (TF2)." },
  { id: 12, name: "Figura Matikanetannhauser", price: 30000,
    img: ASSETS + "mambo.png",
    images: [ASSETS + "mambo.png"],
    desc: "Figura de Uma Musume." },
  { id: 13, name: "Figura Kasane Teto", price: 50000,
    img: ASSETS + "gorda.png",
    images: [ASSETS + "gorda.png"],
    desc: "Figura de Synthesizer V." },
  { id: 14, name: "Peluche Gengar", price: 32000,
    img: ASSETS + "gengar.png",
    images: [ASSETS + "gengar.png"],
    desc: "Peluche de la saga Pokémon." },
  { id: 15, name: "Peluche Jimbo", price: 15000,
    img: ASSETS + "jimbo.png",
    images: [ASSETS + "jimbo.png"],
    desc: "Peluche del videojuego Balatro." }
];

window.getProductById = function(id) {
  return window.products.find(p => String(p.id) === String(id));
};

